'use strict';

const TOOLKIT_VERSION = '4.0.0';

const CATEGORY_MODULES = {
  core: [
    'grab-playwright',
    'grab',
    'mirror',
    'pro-mirror',
    'super-mirror',
  ],
  analyzers: [
    'a11y-checker',
    'asset-inventory',
    'broken-image-checker',
    'canonical-auditor',
    'color-palette-extractor',
    'content-gap-analyzer',
    'cookie-auditor',
    'core-web-vitals-probe',
    'css-coverage-analyzer',
    'dead-link-spider',
    'dom-diff',
    'email-spider',
    'heading-auditor',
    'html5-validator',
    'internal-link-auditor',
    'javascript-footprint-analyzer',
    'keyword-density-analyzer',
    'malware-scanner',
    'meta-duplication-checker',
    'mobile-readiness-checker',
    'open-graph-auditor',
    'payload-size-analyzer',
    'readability-scorer',
    'redirect-auditor',
    'response-header-auditor',
    'schema-validator',
    'security-headers-auditor',
    'semantic-structure-analyzer',
    'seo-auditor',
    'site-taxonomy-mapper',
    'tech-fingerprinter',
    'tracker-radar',
    'typography-analyzer',
    'unused-css',
    'xss-fuzzer',
  ],
  'auth-helpers': [
    '2captcha-auto',
    'api-key-injector',
    'auth-header-forger',
    'basic-auth',
    'canvas-defender',
    'cf-clearance-puller',
    'cookie-cloner',
    'cookie-exporter',
    'cookie-importer',
    'credential-prompt',
    'csrf-form-crawler',
    'csrf-token-miner',
    'hcaptcha-solver',
    'header-token-miner',
    'headless-login-bot',
    'jwt-extractor',
    'login-form-detector',
    'mfa-code-helper',
    'oauth-grabber',
    'oauth-state-decoder',
    'password-spray-simulator',
    'pkce-generator',
    'proxy-auth-tester',
    'request-signer',
    'session-cookie-auditor',
    'session-keepalive',
    'signed-url-helper',
    'tls-fingerprint-randomizer',
    'token-cache',
    'token-decoder',
    'token-refresh-simulator',
    'totp-generator',
    'user-agent-spoofer',
    'web-storage-dumper',
    'x-api-key-helper',
  ],
  exporters: [
    'asset-manifest-builder',
    'content-bundle',
    'diff-reporter',
    'feed-builder',
    'html-cleaner',
    'image-optimizer',
    'jsonl-exporter',
    'link-graph-viz',
    'ndjson-exporter',
    'openapi-seed-exporter',
    'parquet-prep',
    'prompt-dataset-builder',
    'raw-html-archiver',
    'schema-extractor',
    'screenshot-contact-sheet',
    'selector-dump',
    'site-map-exporter',
    'snapshot-packager',
    'table-normalizer',
    'text-bundle',
    'text-extractor',
    'to-csv',
    'to-har',
    'to-json',
    'to-markdown',
    'to-pdf',
    'to-sqlite',
    'to-warc',
    'to-zip',
    'url-list-exporter',
    'vector-ready-exporter',
    'web-archive-indexer',
    'xlsx-ready-exporter',
    'yaml-exporter',
    'zip-manifest-builder',
  ],
  integrations: [
    'airtable-sync',
    'algolia-sync',
    'aws-s3-uploader',
    'azure-blob-uploader',
    'bigquery-loader',
    'clickhouse-writer',
    'datadog-event-pusher',
    'discord-webhook',
    'dropbox-backup',
    'elastic-ingester',
    'firebase-sink',
    'ftp-sync',
    'gcs-uploader',
    'github-pages-deploy',
    'google-sheets-pusher',
    'hubspot-sync',
    'kafka-producer',
    'meilisearch-loader',
    'mongo-importer',
    'n8n-webhook',
    'notion-importer',
    'opensearch-bulk-loader',
    'pagerduty-alert',
    'pinecone-upserter',
    'postgres-writer',
    'rabbitmq-publisher',
    'redis-queue',
    'salesforce-sync',
    'segment-track',
    'sentry-release-note',
    'slack-alerter',
    'snowflake-loader',
    'teams-notifier',
    'webdav-sync',
    'zapier-webhook',
  ],
  monitors: [
    'archive-pusher',
    'availability-probe',
    'certificate-expiry-monitor',
    'change-detector',
    'content-drift-monitor',
    'content-watcher',
    'cookie-health-monitor',
    'cron-healthcheck',
    'cron-runner',
    'dom-change-monitor',
    'feed-watchdog',
    'form-change-monitor',
    'header-inspector',
    'inventory-monitor',
    'keyword-watcher',
    'latency-tracker',
    'link-checker',
    'perf-auditor',
    'price-tracker',
    'redirect-tracer',
    'robots-watchdog',
    'schema-change-monitor',
    'screenshot-diff',
    'search-result-monitor',
    'selector-monitor',
    'session-logger',
    'snapshot-rotator',
    'ssl-checker',
    'statuspage-checker',
    'tls-watchdog',
    'uptime-monitor',
    'visual-regression-monitor',
    'webhook-notifier',
    'webhook-retry-monitor',
    'word-count-monitor',
  ],
  scrapers: [
    'api-scraper',
    'auth-scraper',
    'blog-scraper',
    'catalog-scraper',
    'contact-scraper',
    'dark-web-scraper',
    'directory-scraper',
    'docs-scraper',
    'ecommerce-scraper',
    'event-scraper',
    'faq-scraper',
    'form-mapper',
    'forum-scraper',
    'headless-recorder',
    'image-scraper',
    'job-board-scraper',
    'knowledge-base-scraper',
    'link-harvester',
    'listing-scraper',
    'map-result-scraper',
    'news-scraper',
    'pdf-scraper',
    'podcast-scraper',
    'pricing-page-scraper',
    'product-review-scraper',
    'property-scraper',
    'qa-scraper',
    'rss-scraper',
    'search-result-scraper',
    'social-scraper',
    'spa-scraper',
    'table-scraper',
    'testimonial-scraper',
    'video-scraper',
    'wp-scraper',
  ],
  utils: [
    'asset-cache',
    'backoff-helper',
    'batch-runner',
    'captcha-solver',
    'cli-banner',
    'concurrency-tuner',
    'config-merger',
    'cookie-jar',
    'cookie-normalizer',
    'css-rewriter',
    'csv-flattener',
    'domain-groupper',
    'header-builder',
    'html-rewriter',
    'json-flattener',
    'link-extractor',
    'mime-sniffer',
    'output-organizer',
    'progress-ui',
    'proxy-rotator',
    'queue-manager',
    'rate-limiter',
    'report-gen',
    'request-profiler',
    'retry-helper',
    'robot-parser',
    'selector-tester',
    'sitemap-gen',
    'slugifier',
    'stealth-browser',
    'text-cleaner',
    'url-deduper',
    'url-normalizer',
    'viewport-presets',
    'workspace-cleaner',
  ],
};

const CATEGORY_LABELS = {
  core: 'Core',
  analyzers: 'Analyzers',
  'auth-helpers': 'Auth Helpers',
  exporters: 'Exporters',
  integrations: 'Integrations',
  monitors: 'Monitors',
  scrapers: 'Scrapers',
  utils: 'Utils',
};

function toTitleCase(value) {
  return value
    .split('-')
    .map((part) => (part ? part[0].toUpperCase() + part.slice(1) : part))
    .join(' ');
}

function inferFocus(slug) {
  const tokenPairs = [
    ['api', 'api'],
    ['asset', 'assets'],
    ['auth', 'auth'],
    ['canonical', 'canonical'],
    ['color', 'colors'],
    ['content', 'content'],
    ['cookie', 'cookies'],
    ['cron', 'schedule'],
    ['csv', 'tabular'],
    ['directory', 'directory'],
    ['discord', 'notifications'],
    ['dom', 'dom'],
    ['email', 'emails'],
    ['event', 'events'],
    ['faq', 'faq'],
    ['feed', 'feed'],
    ['form', 'forms'],
    ['header', 'headers'],
    ['heading', 'headings'],
    ['html', 'html'],
    ['image', 'images'],
    ['inventory', 'inventory'],
    ['job', 'jobs'],
    ['json', 'json'],
    ['keyword', 'keywords'],
    ['latency', 'latency'],
    ['link', 'links'],
    ['malware', 'security'],
    ['markdown', 'markdown'],
    ['meta', 'metadata'],
    ['monitor', 'monitoring'],
    ['news', 'articles'],
    ['oauth', 'oauth'],
    ['pdf', 'documents'],
    ['price', 'pricing'],
    ['product', 'products'],
    ['property', 'properties'],
    ['proxy', 'network'],
    ['qa', 'answers'],
    ['queue', 'queue'],
    ['rate', 'throttling'],
    ['redirect', 'redirects'],
    ['report', 'reports'],
    ['rss', 'feed'],
    ['schema', 'schema'],
    ['screenshot', 'snapshots'],
    ['search', 'search'],
    ['seo', 'seo'],
    ['session', 'sessions'],
    ['site', 'site'],
    ['slack', 'notifications'],
    ['social', 'profiles'],
    ['spa', 'spa'],
    ['sql', 'database'],
    ['sqlite', 'database'],
    ['ssl', 'tls'],
    ['table', 'tables'],
    ['text', 'text'],
    ['token', 'tokens'],
    ['totp', 'otp'],
    ['tracker', 'tracking'],
    ['url', 'urls'],
    ['video', 'videos'],
    ['visual', 'visual'],
    ['watcher', 'monitoring'],
    ['webhook', 'webhooks'],
    ['wordpress', 'wordpress'],
    ['wp', 'wordpress'],
    ['xss', 'security'],
    ['yaml', 'yaml'],
    ['zip', 'archives'],
  ];

  for (const [needle, focus] of tokenPairs) {
    if (slug.includes(needle)) {
      return focus;
    }
  }

  return 'general';
}

function describeModule(category, slug) {
  const title = toTitleCase(slug);
  const focus = inferFocus(slug);

  const templates = {
    core: `${title} is a high-power core workflow for large crawling and mirroring jobs.`,
    analyzers: `${title} inspects ${focus} signals and produces a structured audit summary.`,
    'auth-helpers': `${title} prepares and validates ${focus} data for authenticated scraping flows.`,
    exporters: `${title} converts collected ${focus} data into reusable output artifacts.`,
    integrations: `${title} packages ${focus} results for downstream services and delivery targets.`,
    monitors: `${title} tracks ${focus} changes and emits compact state snapshots for automation.`,
    scrapers: `${title} extracts ${focus} data from live pages with resilient parsing defaults.`,
    utils: `${title} provides reusable ${focus} helpers to support large scraping runs efficiently.`,
  };

  return templates[category];
}

function buildDefinition(category, slug) {
  return {
    id: `${category}/${slug}`,
    category,
    categoryLabel: CATEGORY_LABELS[category],
    slug,
    filePath: `${category}/${slug}.js`,
    name: toTitleCase(slug),
    version: TOOLKIT_VERSION,
    focus: inferFocus(slug),
    description: describeModule(category, slug),
    runtime: category === 'core' ? 'native' : 'shared',
  };
}

const ALL_MODULES = Object.entries(CATEGORY_MODULES)
  .flatMap(([category, slugs]) => slugs.map((slug) => buildDefinition(category, slug)));

const MODULE_MAP = new Map(ALL_MODULES.map((moduleDefinition) => [moduleDefinition.id, moduleDefinition]));

function getAllModules() {
  return ALL_MODULES.slice();
}

function getModulesByCategory(category) {
  return getAllModules().filter((moduleDefinition) => moduleDefinition.category === category);
}

function getModuleById(id) {
  return MODULE_MAP.get(id);
}

function getModuleCount() {
  return ALL_MODULES.length;
}

module.exports = {
  CATEGORY_LABELS,
  CATEGORY_MODULES,
  TOOLKIT_VERSION,
  getAllModules,
  getModuleById,
  getModuleCount,
  getModulesByCategory,
};
