'use strict';
/**
 * ╔════════════════════════════════════════════════════════════════════════════╗
 * ║ WebArsenal v5.5.0 "Pulse" - Advanced Security Suite                          ║
 * ║ De{c0}ded by Edwin Dev                                                      ║
 * ║ Module: module-catalog.js                                                          ║
 * ╚════════════════════════════════════════════════════════════════════════════╝
 */




const TOOLKIT_VERSION = '5.5.0';

const CATEGORY_MODULES = {
  core: [
    'attack-graph-viz',
    'automatic-bug-hunter',
    'exploit-path-finder',
    'grab',
    'grab-playwright',
    'headless-recorder',
    'mirror',
    'multi-target-mirror',
    'parallel-target-fuzzer',
    'payload-permutation-engine',
    'pro-mirror',
    'recon-workflow-orchestrator',
    'recursive-domain-mapper',
    'stealth-bypass-runner',
    'stealth-crawler',
    'super-mirror',
    'threat-model-generator',
    'vulnerability-autopilot',
  ],
  analyzers: [
    'a11y-checker',
    'android-intent-auditor',
    'ansible-vault-cracker',
    'api-key-validator',
    'api-response-analyzer',
    'asn-ip-extractor',
    'asset-inventory',
    'aws-iam-policy-auditor',
    'azure-ad-app-auditor',
    'azure-functions-miner',
    'broken-image-checker',
    'cache-poisoning-fuzzer',
    'canonical-auditor',
    'clickjacking-auditor',
    'cloud-metadata-pivot',
    'color-palette-extractor',
    'content-gap-analyzer',
    'cookie-attribute-auditor',
    'cookie-auditor',
    'cookie-security-mapper',
    'core-web-vitals-probe',
    'cors-misconfig-advanced',
    'css-coverage-analyzer',
    'dead-link-spider',
    'dependency-version-monitor',
    'dns-dmarc-auditor',
    'dns-spf-checker',
    'docker-config-auditor',
    'dom-diff',
    'ec2-instance-meta',
    'email-spider',
    'error-detail-miner',
    'expo-dev-config-auditor',
    'favicon-hash-finder',
    'form-action-auditor',
    'gcp-cloud-run-auditor',
    'gcp-iam-leak-checker',
    'github-secrets-miner',
    'gitlab-ci-auditor',
    'heading-auditor',
    'hidden-directory-bruter',
    'host-header-injection',
    'html5-validator',
    'idor-fuzzer',
    'internal-link-auditor',
    'invisible-param-finder',
    'ios-deep-link-fuzzer',
    'javascript-footprint-analyzer',
    'jenkins-info-leak',
    'jenkins-plugin-scanner',
    'k8s-dashboard-checker',
    'k8s-rbac-mapper',
    'k8s-secret-exporter',
    'keyword-density-analyzer',
    'lambda-function-enumerator',
    'lambda-metadata-hunter',
    'lfi-path-traversal',
    'malware-scanner',
    'meta-duplication-checker',
    'mobile-endpoint-mapper',
    'mobile-readiness-checker',
    'oauth-redirect-fuzzer',
    'open-graph-auditor',
    'open-redirect-v2',
    'parameter-pollution-adv',
    'payload-size-analyzer',
    'pii-exposure-detector',
    'postmessage-logger',
    'prototype-pollution-finder',
    'rce-fuzzer',
    'readability-scorer',
    'redirect-auditor',
    'response-header-auditor',
    'schema-validator',
    'security-headers-auditor',
    'security-headers-ranker',
    'semantic-structure-analyzer',
    'seo-auditor',
    'session-timeout-checker',
    'shodan-vuln-mapper',
    'site-taxonomy-mapper',
    'software-version-mapper',
    'spf-dmarc-dkim-auditor',
    'sqli-fuzzer',
    'ssl-cipher-auditor',
    'ssrf-hunter',
    'ssti-auditor',
    'subdomain-takeover-v2',
    'sub-takeover-checker',
    'tech-fingerprinter',
    'terraform-drift-detector',
    'tracker-radar',
    'typography-analyzer',
    'unused-css',
    'vulnerability-fingerprinter',
    'waf-detector',
    'xss-fuzzer',
    'xss-scanner',
  ],
  'auth-helpers': [
    '2captcha-auto',
    '2fa-bypass-tester',
    'account-takeover-chain',
    'api-key-injector',
    'auth-header-forger',
    'basic-auth',
    'broken-object-auth-tester',
    'canvas-defender',
    'cf-clearance-puller',
    'cookie-cloner',
    'cookie-exporter',
    'cookie-importer',
    'cookie-samesite-tester',
    'credential-prompt',
    'csrf-form-crawler',
    'csrf-token-miner',
    'hcaptcha-solver',
    'header-token-miner',
    'headless-login-bot',
    'idor-parameter-fuzzer',
    'jwt-alg-none-tester',
    'jwt-brute-forcer',
    'jwt-extractor',
    'login-form-detector',
    'login-session-recorder',
    'mfa-code-helper',
    'oauth-grabber',
    'oauth-pkce-tester',
    'oauth-state-decoder',
    'password-reset-poison',
    'password-spray-simulator',
    'pkce-generator',
    'rate-limit-tester',
    'request-signer',
    'saml-decoder',
    'session-cookie-auditor',
    'session-fixation-tester',
    'session-keepalive',
    'signed-url-helper',
    'tls-fingerprint-randomizer',
    'token-cache',
    'token-decoder',
    'token-entropy-analyzer',
    'token-refresh-simulator',
    'totp-generator',
    'user-agent-spoofer',
    'web-storage-dumper',
    'x-api-key-helper',
  ],
  exporters: [
    'asset-manifest-builder',
    'bugcrowd-report-exporter',
    'burp-findings-importer',
    'cloned-site-package-exporter',
    'content-bundle',
    'diff-reporter',
    'feed-builder',
    'hackerone-report-exporter',
    'html-cleaner',
    'image-optimizer',
    'jsonl-exporter',
    'link-graph-viz',
    'ndjson-exporter',
    'nuclei-findings-importer',
    'openapi-seed-exporter',
    'parquet-prep',
    'prompt-dataset-builder',
    'raw-html-archiver',
    'schema-extractor',
    'screenshot-contact-sheet',
    'selector-dump',
    'site-map-exporter',
    'snapshot-packager',
    'table-normalizer',
    'text-bundle',
    'text-extractor',
    'to-csv',
    'to-har',
    'to-json',
    'to-markdown',
    'to-pdf',
    'to-sqlite',
    'to-warc',
    'to-zip',
    'url-list-exporter',
    'vector-ready-exporter',
    'video-poc-recorder',
    'web-archive-indexer',
    'xlsx-ready-exporter',
    'yaml-exporter',
    'zip-manifest-builder',
  ],
  integrations: [
    'airtable-sync',
    'algolia-sync',
    'argocd-config-hunter',
    'aws-s3-uploader',
    'azure-blob-uploader',
    'azure-devops-auditor',
    'bigquery-loader',
    'bitbucket-pipeline-miner',
    'circle-ci-leak-hunter',
    'clickhouse-writer',
    'datadog-event-pusher',
    'discord-webhook',
    'drone-ci-scanner',
    'dropbox-backup',
    'elastic-ingester',
    'firebase-sink',
    'ftp-sync',
    'gcs-uploader',
    'github-pages-deploy',
    'github-workflow-auditor',
    'gitlab-ci-scanner',
    'google-sheets-pusher',
    'hubspot-sync',
    'jenkins-job-parser',
    'kafka-producer',
    'meilisearch-loader',
    'mongo-importer',
    'n8n-webhook',
    'notion-importer',
    'opensearch-bulk-loader',
    'pagerduty-alert',
    'pinecone-upserter',
    'postgres-writer',
    'rabbitmq-publisher',
    'redis-queue',
    'salesforce-sync',
    'segment-track',
    'sentry-release-note',
    'slack-alerter',
    'snowflake-loader',
    'spinnaker-leak-auditor',
    'teams-notifier',
    'travis-ci-checker',
    'webdav-sync',
    'zapier-webhook',
  ],
  monitors: [
    'api-key-leak-monitor',
    'archive-pusher',
    'availability-probe',
    'breach-monitor',
    'bug-bounty-scope-monitor',
    'certificate-expiry-monitor',
    'change-detector',
    'content-drift-monitor',
    'content-watcher',
    'cookie-health-monitor',
    'cron-healthcheck',
    'cron-runner',
    'dom-change-monitor',
    'exposed-service-monitor',
    'feed-watchdog',
    'form-change-monitor',
    'header-inspector',
    'inventory-monitor',
    'js-change-monitor',
    'keyword-watcher',
    'latency-tracker',
    'link-checker',
    'new-endpoint-monitor',
    'perf-auditor',
    'price-tracker',
    'redirect-tracer',
    'robots-watchdog',
    'schema-change-monitor',
    'screenshot-diff',
    'search-result-monitor',
    'selector-monitor',
    'session-logger',
    'snapshot-rotator',
    'ssl-checker',
    'statuspage-checker',
    'subdomain-new-host-monitor',
    'tls-certificate-monitor',
    'tls-watchdog',
    'uptime-monitor',
    'visual-regression-monitor',
    'webhook-notifier',
    'webhook-retry-monitor',
    'word-count-monitor',
  ],
  reporters: [
    'csv-vuln-exporter',
    'diff-reporter',
    'discord-webhook-notifier',
    'final-master-runner',
    'jira-ticket-creator',
    'pdf-recon-summary',
    'scope-mapper',
    'slack-notification-hook',
    'vuln-reporter',
  ],
  scrapers: [
    'android-manifest-checker',
    'authenticated-browser-capture',
    'api-key-validator',
    'api-scraper',
    'asset-dependency-mapper',
    'asset-manifest-scraper',
    'auth-scraper',
    'azure-blob-checker',
    'azure-storage-miner',
    'bing-dorker',
    'blog-scraper',
    'browser-action-crawler',
    'browser-site-crawler',
    'catalog-scraper',
    'cdn-origin-finder',
    'certificate-transparency-miner',
    'comment-sensitive-data',
    'component-class-extractor',
    'common-crawl-miner',
    'contact-scraper',
    'cors-origin-tester',
    'css-color-token-extractor',
    'css-bundle-extractor',
    'css-selector-extractor',
    'css-variable-extractor',
    'couchdb-user-auditor',
    'crtsh-subdomain-monitor',
    'dark-web-scraper',
    'directory-scraper',
    'dom-snapshot-scraper',
    'dom-id-map-extractor',
    'docker-registry-scanner',
    'docs-scraper',
    'ecommerce-scraper',
    'elasticsearch-index-lister',
    'electron-binary-extractor',
    'event-scraper',
    'faq-scraper',
    'firebase-config-extractor',
    'firebase-db-auditor',
    'font-asset-extractor',
    'full-site-workspace-builder',
    'frontend-resource-extractor',
    'flutter-api-extractor',
    'form-mapper',
    'forum-scraper',
    'gcp-bucket-hunter',
    'github-action-leak',
    'google-dorker',
    'graphql-batch-scanner',
    'graphql-endpoint-spider',
    'grpc-endpoint-discovery',
    'grpc-endpoint-finder',
    'headless-recorder',
    'html-comment-extractor',
    'html-css-js-scraper',
    'html-section-scraper',
    'html-source-extractor',
    'image-asset-downloader',
    'image-scraper',
    'influxdb-leak-checker',
    'inline-script-extractor',
    'inline-style-extractor',
    'job-board-scraper',
    'js-api-call-extractor',
    'js-bundle-extractor',
    'js-endpoint-extractor',
    'js-library-detector',
    'js-map-file-hunter',
    'js-route-extractor',
    'knowledge-base-scraper',
    'linked-asset-downloader',
    'link-harvester',
    'link-health-checker',
    'listing-scraper',
    'map-result-scraper',
    'memcached-item-sniffer',
    'media-query-extractor',
    'mobile-endpoint-extractor',
    'mobile-plist-auditor',
    'mobile-secret-harvester',
    'mongodb-schema-miner',
    'news-scraper',
    'open-s3-hunter',
    'param-miner-v2',
    'pdf-scraper',
    'podcast-scraper',
    'pricing-page-scraper',
    'product-review-scraper',
    'property-scraper',
    'qa-scraper',
    'rabbitmq-queue-sniffer',
    'react-native-bundle-miner',
    'redis-key-dumper',
    'robots-sitemap-spider',
    'robots-txt-analyzer',
    'rss-scraper',
    's3-bucket-finder',
    's3-bucket-lister',
    'search-result-scraper',
    'shodan-dorker',
    'shodan-ip-history',
    'script-link-scraper',
    'page-bundle-downloader',
    'sitemap-harvester',
    'smtp-relay-bruter',
    'snmp-community-bruter',
    'soap-wsdl-parser',
    'social-scraper',
    'source-asset-extractor',
    'source-map-extractor',
    'spa-scraper',
    'stylesheet-link-scraper',
    'table-scraper',
    'terraform-state-hunter',
    'tftp-file-harvester',
    'vault-kv-scanner',
    'video-scraper',
    'wasm-extractor',
    'wayback-machine-url-miner',
    'webrtc-ip-leak-checker',
    'whois-history-parser',
    'wp-scraper',
  ],
  utils: [
    'asset-cache',
    'backoff-helper',
    'batch-runner',
    'burp-collaborator-listener',
    'burp-xml-parser',
    'bypass-encoder',
    'captcha-solver',
    'censys-lookup',
    'cidr-expander',
    'cidr-to-hostnames',
    'cli-banner',
    'concurrency-tuner',
    'config-merger',
    'cookie-jar',
    'cookie-normalizer',
    'css-rewriter',
    'csv-flattener',
    'dedup-urls',
    'diff-engine',
    'dns-record-auditor',
    'dns-resolver',
    'domain-groupper',
    'elasticsearch-head-auditor',
    'final-audit-summary',
    'finding-deduplicator',
    'header-builder',
    'history-logger',
    'html-report-generator',
    'html-rewriter',
    'internal-host-mapper',
    'ip-geolocation-mapper',
    'ip-to-asn-lookup',
    'json-flattener',
    'json-output-cleaner',
    'link-extractor',
    'memcached-dumper',
    'mime-sniffer',
    'mongodb-noauth-checker',
    'nmap-xml-parser',
    'nuclei-template-runner',
    'output-merger',
    'output-organizer',
    'payload-library',
    'port-info-grabber',
    'port-scanner',
    'port-scanner-pro',
    'private-ip-discovery',
    'progress-ui',
    'proxy-rotator',
    'queue-manager',
    'rate-limiter',
    'recon-data-merger',
    'redirect-tracer',
    'redis-info-grabber',
    'report-gen',
    'report-templater',
    'request-profiler',
    'retry-helper',
    'robot-parser',
    'screenshot-diff',
    'severity-scorer',
    'shodan-wrapper',
    'sitemap-gen',
    'slugifier',
    'snmp-walker',
    'stealth-browser',
    'sub-domain-diff',
    'target-profile-builder',
    'text-cleaner',
    'tftp-scanner',
    'url-deduper',
    'url-normalizer',
    'viewport-presets',
    'vuln-severity-sorter',
    'whois-privacy-checker',
    'workspace-diff-builder',
    'workspace-integrity-validator',
    'workspace-qa-validator',
    'workspace-cleaner',
  ],
  'vuln-probes': [
    'cache-deception-tester',
    'cache-poisoning-probe',
    'clickjacking-tester',
    'command-injection-tester',
    'cors-misconfiguration-checker',
    'crlf-injection-tester',
    'csv-injection-tester',
    'dns-rebinding-tester',
    'dom-xss-scanner',
    'email-header-injection-tester',
    'graphql-introspection-probe',
    'host-header-injection-tester',
    'http-desync-tester',
    'http-parameter-pollution-tester',
    'java-deserialization-tester',
    'jsonp-hijacking-tester',
    'jwt-confusion-tester',
    'ldap-injection-tester',
    'lfi-path-traversal-tester',
    'markdown-injection-tester',
    'mass-assignment-tester',
    'node-prototype-pollution-tester',
    'nosql-injection-tester',
    'open-redirect-confirmer',
    'path-traversal-tester',
    'pdf-injection-tester',
    'php-object-injection-tester',
    'privilege-escalation-tester',
    'prototype-pollution-scanner',
    'python-pickle-tester',
    'race-condition-tester',
    'redos-tester',
    'request-smuggling-probe',
    'second-order-injection-tester',
    'sqli-error-detector',
    'ssrf-probe',
    'ssti-detector',
    'subdomain-takeover-detector',
    'timing-attack-probe',
    'websocket-hijacking-tester',
    'xml-injection-tester',
    'xxe-tester',
  ],
  'api-security': [
    'api-key-rotation-checker',
    'api-rate-limit-bypasser',
    'api-versioning-bypass',
    'api-versioning-probe',
    'graphql-authorization-tester',
    'graphql-batch-attack-tester',
    'graphql-query-depth-tester',
    'grpc-fuzzer',
    'http-method-tester',
    'mass-assignment-deep-tester',
    'rest-api-fuzzer',
    'swagger-openapi-exposer',
  ],
  mobile: [
    'android-deeplink-scraper',
    'apk-manifest-analyzer',
    'ios-plist-analyzer',
    'mobile-endpoint-extractor',
  ],
  cloud: [
    'azure-blob-tester',
    'cloud-metadata-probe',
    'gcp-bucket-tester',
    'iam-misconfiguration-checker',
    'lambda-function-url-finder',
    's3-bucket-tester',
  ],
  recon: [
    'api-gateway-probe',
    'asn-mapper',
    'breach-data-checker',
    'certificate-transparency-scraper',
    'cloud-asset-enumerator',
    'dns-brute-forcer',
    'github-secrets-scraper',
    'google-dork-runner',
    'internet-archive-differ',
    'passive-recon-runner',
    'shodan-scraper',
    'unicode-normalizer-tester',
    'wayback-diff-scraper',
    'whois-analyzer',
  ],
  web3: [
    'defi-price-oracle-tester',
    'nft-metadata-probe',
    'smart-contract-scanner',
    'wallet-connect-analyzer',
  ],
  infrastructure: [
    'ci-cd-exposure-finder',
    'client-side-template-injection-tester',
    'dependency-confusion-checker',
    'elasticsearch-exposure-checker',
    'electron-app-auditor',
    'firewall-bypass-tester',
    'graphql-authorization-tester',
    'iframe-sandbox-tester',
    'internal-microservice-prober',
    'kubernetes-dashboard-finder',
    'load-balancer-fingerprinter',
    'log4shell-probe',
    'memcached-exposure-checker',
    'mongodb-exposure-checker',
    'redis-exposure-checker',
    'reverse-proxy-confusion-tester',
    'smtp-relay-tester',
    'spring4shell-probe',
    'virtual-host-fuzzer',
    'webassembly-analyzer',
    'zip-slip-payload-tester',
  ],
};

const CATEGORY_LABELS = {
  core: 'Core',
  analyzers: 'Analyzers',
  'auth-helpers': 'Auth Helpers',
  exporters: 'Exporters',
  integrations: 'Integrations',
  monitors: 'Monitors',
  reporters: 'Reporters',
  scrapers: 'Scrapers',
  utils: 'Utils',
  'vuln-probes': 'Vulnerability Probes',
  'api-security': 'API Security',
  mobile: 'Mobile',
  cloud: 'Cloud',
  recon: 'Recon',
  web3: 'Web3',
  infrastructure: 'Infrastructure',
};

function toTitleCase(value) {
  return value
    .split('-')
    .map((part) => (part ? part[0].toUpperCase() + part.slice(1) : part))
    .join(' ');
}

function inferFocus(slug) {
  const tokenPairs = [
    ['api', 'api'],
    ['asset', 'assets'],
    ['auth', 'auth'],
    ['browser', 'browser'],
    ['canonical', 'canonical'],
    ['component', 'components'],
    ['css', 'stylesheets'],
    ['color', 'colors'],
    ['content', 'content'],
    ['cookie', 'cookies'],
    ['cron', 'schedule'],
    ['csv', 'tabular'],
    ['directory', 'directory'],
    ['diff', 'diff'],
    ['discord', 'notifications'],
    ['dom', 'dom'],
    ['email', 'emails'],
    ['event', 'events'],
    ['faq', 'faq'],
    ['feed', 'feed'],
    ['font', 'fonts'],
    ['frontend', 'frontend'],
    ['form', 'forms'],
    ['header', 'headers'],
    ['heading', 'headings'],
    ['html', 'html'],
    ['image', 'images'],
    ['inventory', 'inventory'],
    ['job', 'jobs'],
    ['js', 'javascript'],
    ['json', 'json'],
    ['keyword', 'keywords'],
    ['latency', 'latency'],
    ['link', 'links'],
    ['malware', 'security'],
    ['markdown', 'markdown'],
    ['meta', 'metadata'],
    ['monitor', 'monitoring'],
    ['news', 'articles'],
    ['oauth', 'oauth'],
    ['pdf', 'documents'],
    ['price', 'pricing'],
    ['product', 'products'],
    ['property', 'properties'],
    ['proxy', 'network'],
    ['qa', 'answers'],
    ['queue', 'queue'],
    ['rate', 'throttling'],
    ['redirect', 'redirects'],
    ['report', 'reports'],
    ['rss', 'feed'],
    ['schema', 'schema'],
    ['script', 'javascript'],
    ['screenshot', 'snapshots'],
    ['search', 'search'],
    ['seo', 'seo'],
    ['session', 'sessions'],
    ['site', 'site'],
    ['slack', 'notifications'],
    ['social', 'profiles'],
    ['spa', 'spa'],
    ['sql', 'database'],
    ['sqlite', 'database'],
    ['ssl', 'tls'],
    ['style', 'stylesheets'],
    ['table', 'tables'],
    ['text', 'text'],
    ['token', 'tokens'],
    ['totp', 'otp'],
    ['tracker', 'tracking'],
    ['url', 'urls'],
    ['video', 'videos'],
    ['visual', 'visual'],
    ['workspace', 'workspace'],
    ['watcher', 'monitoring'],
    ['webhook', 'webhooks'],
    ['wordpress', 'wordpress'],
    ['wp', 'wordpress'],
    ['xss', 'security'],
    ['yaml', 'yaml'],
    ['zip', 'archives'],
  ];

  for (const [needle, focus] of tokenPairs) {
    if (slug.includes(needle)) {
      return focus;
    }
  }

  return 'general';
}

function describeModule(category, slug) {
  const title = toTitleCase(slug);
  const focus = inferFocus(slug);

  const templates = {
    core: `${title} is a high-power core workflow for large crawling and mirroring jobs.`,
    analyzers: `${title} inspects ${focus} signals and produces a structured audit summary.`,
    'auth-helpers': `${title} prepares and validates ${focus} data for authenticated scraping flows.`,
    exporters: `${title} converts collected ${focus} data into reusable output artifacts.`,
    integrations: `${title} packages ${focus} results for downstream services and delivery targets.`,
    monitors: `${title} tracks ${focus} changes and emits compact state snapshots for automation.`,
    reporters: `${title} generates detailed ${focus} findings and transmits security reports.`,
    scrapers: `${title} extracts ${focus} data from live pages with resilient parsing defaults.`,
    utils: `${title} provides reusable ${focus} helpers to support large scraping runs efficiently.`,
    'vuln-probes': `${title} actively tests for ${focus} vulnerabilities with automated attack payloads.`,
    'api-security': `${title} probes ${focus} endpoints for configuration weaknesses and auth bypasses.`,
    mobile: `${title} performs static and dynamic analysis of ${focus} assets in mobile applications.`,
    cloud: `${title} hunts for misconfigurations and data leaks across ${focus} cloud infrastructure.`,
    recon: `${title} automates horizontal and vertical ${focus} discovery across the target attack surface.`,
    web3: `${title} audits ${focus} smart contracts and decentralized application logic for flaws.`,
    infrastructure: `${title} evaluates ${focus} server and network configurations for security exposure.`,
  };

  return templates[category];
}

function buildDefinition(category, slug) {
  return {
    id: `${category}/${slug}`,
    category,
    categoryLabel: CATEGORY_LABELS[category],
    slug,
    filePath: `${category}/${slug}.js`,
    name: toTitleCase(slug),
    version: TOOLKIT_VERSION,
    focus: inferFocus(slug),
    description: describeModule(category, slug),
    runtime: category === 'core' ? 'native' : 'shared',
  };
}

const ALL_MODULES = Object.entries(CATEGORY_MODULES)
  .flatMap(([category, slugs]) => slugs.map((slug) => buildDefinition(category, slug)));

const MODULE_MAP = new Map(ALL_MODULES.map((moduleDefinition) => [moduleDefinition.id, moduleDefinition]));

function getAllModules() {
  return ALL_MODULES.slice();
}

function getModulesByCategory(category) {
  return getAllModules().filter((moduleDefinition) => moduleDefinition.category === category);
}

function getModuleById(id) {
  return MODULE_MAP.get(id);
}

function getModuleCount() {
  return ALL_MODULES.length;
}

module.exports = {
  CATEGORY_LABELS,
  CATEGORY_MODULES,
  TOOLKIT_VERSION,
  getAllModules,
  getModuleById,
  getModuleCount,
  getModulesByCategory,
};
